export class editionModel{
    edition_id:any
	edition_name:any
	edition_alias:any
	edition_date:any
	parent_category:any
	description:any
	status:any
	createdby:any
	customer_id:any
	edition_image:any
	edition_pdf:any
	add_to_home:any
	meta_desc:any
	meta_keywords:any
	media_ext:any
	filetype:any
	base64file:any
	flag:any
}